-- Claude EDR event storage schema
-- WAL mode and PRAGMAs are set in sqlite_store.py (must run outside transactions)

-- Endpoints (machines running the EDR sensor)
CREATE TABLE IF NOT EXISTS endpoints (
    id TEXT PRIMARY KEY,
    hostname TEXT NOT NULL,
    os_name TEXT,
    os_version TEXT,
    kernel TEXT,
    arch TEXT,
    ip_addresses_json TEXT,
    username TEXT,
    cpu_count INTEGER,
    memory_total_gb REAL,
    agent_count INTEGER DEFAULT 0,
    first_seen TEXT NOT NULL,
    last_heartbeat TEXT NOT NULL,
    status TEXT DEFAULT 'online'
);

CREATE INDEX IF NOT EXISTS idx_endpoints_hostname ON endpoints(hostname);
CREATE INDEX IF NOT EXISTS idx_endpoints_status ON endpoints(status);

-- Agent sessions
CREATE TABLE IF NOT EXISTS agent_sessions (
    session_id TEXT PRIMARY KEY,
    agent_type TEXT NOT NULL,
    root_pid INTEGER NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT,
    working_directory TEXT,
    username TEXT,
    process_tree_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_agent_type ON agent_sessions(agent_type);
CREATE INDEX IF NOT EXISTS idx_sessions_start_time ON agent_sessions(start_time);

-- Core events table (append-only, time-series)
CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    category TEXT NOT NULL,
    action TEXT NOT NULL,
    severity INTEGER DEFAULT 0,
    -- Agent context
    agent_type TEXT,
    agent_session_id TEXT,
    agent_pid INTEGER,
    working_directory TEXT,
    tool_name TEXT,
    tool_input_json TEXT,
    tool_response_json TEXT,
    -- Process context
    process_pid INTEGER,
    process_ppid INTEGER,
    process_name TEXT,
    process_cmdline TEXT,
    -- File context
    file_path TEXT,
    file_operation TEXT,
    file_size INTEGER,
    -- Network context
    net_direction TEXT,
    net_protocol TEXT,
    net_remote_addr TEXT,
    net_remote_port INTEGER,
    net_domain TEXT,
    -- LLM context
    llm_provider TEXT,
    llm_model TEXT,
    llm_tokens_in INTEGER,
    llm_tokens_out INTEGER,
    llm_has_tools INTEGER,
    llm_contains_credentials INTEGER,
    -- Detection
    risk_score REAL DEFAULT 0.0,
    rule_matches_json TEXT,
    -- Metadata
    sensor_source TEXT,
    raw_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);
CREATE INDEX IF NOT EXISTS idx_events_category ON events(category);
CREATE INDEX IF NOT EXISTS idx_events_action ON events(action);
CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity);
CREATE INDEX IF NOT EXISTS idx_events_agent_session ON events(agent_session_id);
CREATE INDEX IF NOT EXISTS idx_events_agent_type ON events(agent_type);
CREATE INDEX IF NOT EXISTS idx_events_tool_name ON events(tool_name);
CREATE INDEX IF NOT EXISTS idx_events_file_path ON events(file_path);
CREATE INDEX IF NOT EXISTS idx_events_net_remote ON events(net_remote_addr);
CREATE INDEX IF NOT EXISTS idx_events_risk_score ON events(risk_score);

-- Alerts generated by detection engine
CREATE TABLE IF NOT EXISTS alerts (
    id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    rule_id TEXT NOT NULL,
    rule_name TEXT NOT NULL,
    severity INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_ids_json TEXT,
    agent_session_id TEXT,
    agent_type TEXT,
    status TEXT DEFAULT 'open',
    resolved_at TEXT,
    resolved_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_rule_id ON alerts(rule_id);

-- Detection rules (loaded from YAML but tracked in DB)
CREATE TABLE IF NOT EXISTS detection_rules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    severity INTEGER DEFAULT 2,
    rule_type TEXT NOT NULL,
    rule_definition_json TEXT NOT NULL,
    enabled INTEGER DEFAULT 1,
    source_file TEXT,
    created_at TEXT,
    updated_at TEXT
);
